# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-06-17 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220617_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='uuid',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
