# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2022-06-17 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220617_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='uuid',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
