version: '3.0'
services:
  flask_server:
    build: /home/matej/Desktop/Megatrend-Selection/ZadatakA/flask_server
    hostname: app
    ports:
      - "5000:5000"
    depends_on:
      - tf_serving
    networks:
      - main
    container_name: app
    restart: on-failure
    volumes:
      - ./flask_server:/flask_server
  tf_serving:
    command:
      - --model_config_file=/models.conf
    image: tensorflow/serving
    networks:
      - main
    ports:
      - "8500:8500"
      - "8501:8501"
    volumes:
      - ./mnist_classifier:/models
      - ./mnist_classifier/models.conf:/models.conf
networks:
  main: