name: django-tests
on: 
  push:
    branches: [main]

jobs:
  start_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create env file
        run:  |
              touch .env
              echo POSTGRES_ENGINE=${{ secrets.POSTGRES_ENGINE }} >> .env
              echo POSTGRES_DATABASE=${{ secrets.POSTGRES_DATABASE }} >> .env
              echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
              echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
              echo POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} >> .env
              echo POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} >> .env
              echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
              echo MINIO_HOST=${{ secrets.MINIO_HOST }} >> .env
              echo MINIO_PORT=${{ secrets.MINIO_PORT }} >> .env
              echo MINIO_ROOT_USER=${{ secrets.MINIO_ROOT_USER }} >> .env
              echo MINIO_ROOT_PASSWORD=${{ secrets.MINIO_ROOT_PASSWORD }} >> .env
              cat .env
              mv .env project/db

      - name: Start containers
        run: 
              docker-compose -f "project/docker-compose.yml" up -d --build

      - name: Check
        run: docker ps -a

  run_django_tests:

    name: Run Django tests        
    runs-on: ubuntu-latest
    steps:

    - name: Sleep 120s until the containers are up
      run: sleep 150

    - name: Run tests
      run: docker exec soda_app python manage.py test

  shut_docker_down:

    name: Shut docker down
    runs-on: ubuntu-latest
    needs: [run_django_tests]

    steps:
    
    - uses: actions/checkout@v3
    - run: docker-compose down --remove-orphans

