name: django-tests
on: 
  push:
    branches: [develop]

jobs:
  start_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Create env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_ENGINE: ${{ secrets.POSTGRES_ENGINE }}
          envkey_POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
          envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          envkey_POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          envkey_POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          envkey_MINIO_HOST: ${{ secrets.MINIO_HOST }}
          envkey_MINIO_PORT: ${{ secrets.MINIO_PORT }}
          envkey_MINIO_ROOT_USER: ${{ secrets.MINIO_ROOT_USER }}
          envkey_MINIO_ROOT_PASSWORD: ${{ secrets.MINIO_ROOT_PASSWORD }}
          directory: project/db

      - name: Start containers
        run: 
              docker-compose -f "project/docker-compose.yml" up -d --build

      - name: Check containers
        run:  |
              sleep 15
              docker ps -a

      - name: Dump docker logs on failure
        uses: jwalton/gh-docker-logs@v1

      - name: Run tests
        run: docker exec soda_app python manage.py test

      - name: Stop containers
        run: docker-compose -f "project/docker-compose.yml" down

