name: django-tests
on: 
  push:
    branches: [main, develop]

jobs:
  start_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create env file
        run:  |
              touch .env
              echo "${{ secrets.MAIN_ENV }}" >> .env
              cat .env
              mv .env project/db

      - name: Start containers
        run: 
              docker-compose -f "project/docker-compose.yml" up -d --build

      - name: Run tests
        run: docker exec soda_app python manage.py test

      - name: Stop containers
        run: docker-compose -f "project/docker-compose.yml" down

